package queries

import (
	"os"
	"strings"
	"testing"
)

func TestDocumentCreateQueriesOnlySetContentRefForLocalUploads(t *testing.T) {
	raw, err := os.ReadFile("documents.sql")
	if err != nil {
		t.Fatalf("read documents.sql: %v", err)
	}
	sql := string(raw)

	tests := []struct {
		name      string
		queryName string
		want      string
	}{
		{
			name:      "legacy create",
			queryName: "CreateDocument",
			want:      "CASE WHEN $2 = 'local-upload' THEN $3 ELSE NULL END",
		},
		{
			name:      "owner create",
			queryName: "CreateDocumentForOwner",
			want:      "CASE WHEN sqlc.arg('source_type') = 'local-upload' THEN sqlc.arg('source_ref') ELSE NULL END",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			query := queryNamed(t, sql, tt.queryName)
			normalized := strings.Join(strings.Fields(query), " ")
			if !strings.Contains(normalized, tt.want) {
				t.Fatalf("%s must contain %q; query = %s", tt.queryName, tt.want, normalized)
			}
		})
	}
}

func TestChecksumQueriesOnlyDedupeLocalUploads(t *testing.T) {
	raw, err := os.ReadFile("documents.sql")
	if err != nil {
		t.Fatalf("read documents.sql: %v", err)
	}
	sql := string(raw)

	tests := []struct {
		queryName string
		want      string
	}{
		{queryName: "FindDocumentByChecksum", want: "source_type = 'local-upload'"},
		{queryName: "FindDocumentByChecksumForOwner", want: "d.source_type = 'local-upload'"},
	}

	for _, tt := range tests {
		t.Run(tt.queryName, func(t *testing.T) {
			query := queryNamed(t, sql, tt.queryName)
			normalized := strings.Join(strings.Fields(query), " ")
			if !strings.Contains(normalized, tt.want) {
				t.Fatalf("%s must contain %q; query = %s", tt.queryName, tt.want, normalized)
			}
		})
	}
}

func TestFeishuCreateBindsOwnedKnowledgeBaseAndOAuthAccount(t *testing.T) {
	raw, err := os.ReadFile("documents.sql")
	if err != nil {
		t.Fatal(err)
	}
	query := strings.Join(strings.Fields(queryNamed(t, string(raw), "CreateFeishuDocumentForOwner")), " ")
	for _, required := range []string{
		"JOIN oauth_accounts AS oa",
		"oa.user_id = sqlc.arg('owner_user_id')",
		"oa.provider = 'feishu'",
		"kb.owner_user_id = sqlc.arg('owner_user_id')",
	} {
		if !strings.Contains(query, required) {
			t.Fatalf("owner-scoped Feishu insert missing %q: %s", required, query)
		}
	}
}

func TestFeishuStateTransitionsUseExpectedActiveAndPendingFields(t *testing.T) {
	raw, err := os.ReadFile("documents.sql")
	if err != nil {
		t.Fatal(err)
	}
	sql := string(raw)
	stage := strings.Join(strings.Fields(queryNamed(t, sql, "StageFeishuSnapshot")), " ")
	for _, required := range []string{
		"sync_status = 'syncing'",
		"remote_revision IS NOT DISTINCT FROM sqlc.narg('expected_remote_revision')::text",
		"checksum = sqlc.arg('expected_checksum')",
		"pending_content_ref IS NULL",
	} {
		if !strings.Contains(stage, required) {
			t.Fatalf("stage query missing %q: %s", required, stage)
		}
	}
	for _, forbidden := range []string{"title =", "bytes =", "metadata ="} {
		if strings.Contains(stage, forbidden) {
			t.Fatalf("stage query mutates active field %q: %s", forbidden, stage)
		}
	}
	promote := strings.Join(strings.Fields(queryNamed(t, sql, "PromoteFeishuSnapshot")), " ")
	for _, required := range []string{"title = sqlc.arg('title')", "bytes = sqlc.arg('bytes')", "metadata = sqlc.arg('metadata')"} {
		if !strings.Contains(promote, required) {
			t.Fatalf("promotion query missing active metadata update %q: %s", required, promote)
		}
	}

	for _, name := range []string{"PromoteFeishuSnapshot", "FailFeishuSync"} {
		query := strings.Join(strings.Fields(queryNamed(t, sql, name)), " ")
		for _, required := range []string{"sync_status = 'syncing'", "pending_content_ref", "pending_checksum", "pending_remote_revision"} {
			if !strings.Contains(query, required) {
				t.Fatalf("%s missing stale-worker guard %q: %s", name, required, query)
			}
		}
	}
}

func TestGeneratedDocumentQueriesRetainSQLCProvenance(t *testing.T) {
	raw, err := os.ReadFile("../generated/documents.sql.go")
	if err != nil {
		t.Fatal(err)
	}
	text := string(raw)
	if !strings.HasPrefix(text, "// Code generated by sqlc. DO NOT EDIT.") {
		t.Fatal("generated document queries are missing sqlc provenance")
	}
	for _, method := range []string{"CreateFeishuDocumentForOwner", "StageFeishuSnapshot", "PromoteFeishuSnapshot", "FailFeishuSync"} {
		if !strings.Contains(text, "func (q *Queries) "+method) {
			t.Fatalf("generated query method %s missing", method)
		}
	}
}

func queryNamed(t *testing.T, sql, name string) string {
	t.Helper()
	startMarker := "-- name: " + name + " "
	start := strings.Index(sql, startMarker)
	if start == -1 {
		t.Fatalf("query %s not found", name)
	}
	rest := sql[start+len(startMarker):]
	if next := strings.Index(rest, "-- name: "); next >= 0 {
		rest = rest[:next]
	}
	return rest
}
